export enum StageSchedulerCode {
    RECRUITMENT = 'RECRUITMENT',
    CAREER_WEEK = 'CAREER_WEEK',
    TEST_WEEK = 'TEST_WEEK',
    CASE_CHAMPIONSHIP = 'CASE_CHAMPIONSHIP',
    EMPLOYERS_MARATHON = 'EMPLOYERS_MARATHON',
    INTERNSHIP_CHOICE = 'INTERNSHIP_CHOICE',
    INTERNSHIP_1 = 'INTERNSHIP_1',
    INTERNSHIP_2 = 'INTERNSHIP_2',
    INTERNSHIP_3 = 'INTERNSHIP_3',
}