name: Deploy to cloud
run-name: ${{ github.actor }} deploying to cloud
on:
  push:
    branches: [ feature/test-branch ]

jobs:
  build-and-deploy-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to SberCloud
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/mos_trainee/mostrainee-front:${{ github.run_number }}
          build-args: SERVER_URL=http://46.243.201.29:8080
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.json
          kubectl --kubeconfig=./kubeconfig.json set image deployment/front front=${{ secrets.REGISTRY_URL }}/mos_trainee/mostrainee-front:${{ github.run_number }}

  build-and-deploy-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Run tests with Maven
        run: mvn test

      - name: Login to SberCloud
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./trainee-service
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/mos_trainee/mostrainee-trainee-service:${{ github.run_number }}
          build-args: MAVEN_ARTIFACT=./target/server-*.jar

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.json
          kubectl --kubeconfig=./kubeconfig.json set image deployment/trainee-service trainee-service=${{ secrets.REGISTRY_URL }}/mos_trainee/mostrainee-trainee-service:${{ github.run_number }}