name: Deploy to cloud
run-name: ${{ github.actor }} is building backend
on:
  push:
    branches: [ 'feature/test-branch' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to SberCloud
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/mos-trainee-front:latest